export {
	HeadlessTextInputBridge,
	type HeadlessTextInputBridgeProps,
} from "./HeadlessTextInputBridge";
export {
	createTextEditingSession,
	isTextSelectionCollapsed,
	normalizeTextSelection,
	resolveTextEditingDecorations,
	resolveTextEditingIndexAtScreenPoint,
	resolveTextEditingOverlayRect,
	resolveTextEditingSelectionFromAnchor,
	type TextEditingDecorations,
	type TextEditingFrame,
	type TextEditingMode,
	type TextEditingPoint,
	type TextEditingRect,
	type TextEditingSelection,
	type TextEditingSession,
	type TextEditingTarget,
	updateTextEditingSessionComposition,
	updateTextEditingSessionDraft,
	updateTextEditingSessionSelection,
	updateTextEditingSessionTarget,
} from "./session";
